### ISSUE TITLE
Problem with registration for the SDK

### ISSUE THREAD

**Issue by bqkhiem96** [Hype-Labs/HypeChatDemo.android#1]
I've tried to subscribe for the SDK on the official website but the registration doesn't direct me anywhere. Hopefully the problem got fixed soon.
Cheers!!

**Comment by Hype-Labs** [comment]
The SDK is currently undergoing a private beta program, meaning that only selected developers are accepted for the program. We're now only a couple of weeks away from going public, but I'll go ahead and accept your subscription. You should get an email with further instructions!

Best regards.

**Comment by bqkhiem96** [comment]
Thank you HypeLabs, I appreciate the opportunity
