### ISSUE TITLE
Android app launch issues on Emulator and Devices

### ISSUE THREAD

**Issue by n-jay** [Hype-Labs/HypeChatDemo.android#3]
When I tried to launch the app on the API 26 emulator, it continuously crashed giving out an ANR dialog:
![screenshot_1528783901](https://user-images.githubusercontent.com/24616975/41286603-9e89e226-6e5d-11e8-922f-c9aed6e46931.png)

The logcat displayed the following error:
`06-12 16:25:20.784 19217-19251/com.hypelabs.hypechatdemo E/BluetoothAdapter: Bluetooth binder is null
06-12 16:25:20.800 19217-19251/com.hypelabs.hypechatdemo W/SystemServiceRegistry: No service published for: wifip2p
06-12 16:25:20.828 19217-19251/com.hypelabs.hypechatdemo E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.hypelabs.hypechatdemo, PID: 19217
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.wifi.p2p.WifiP2pManager$Channel android.net.wifi.p2p.WifiP2pManager.initialize(android.content.Context, android.os.Looper, android.net.wifi.p2p.WifiP2pManager$ChannelListener)' on a null object reference
        at com.hypelabs.hype.drivers.c.l.n(Unknown Source:0)
        at com.hypelabs.hype.drivers.c.l.<init>(Unknown Source:0)
        at com.hypelabs.hype.drivers.d.a(Unknown Source:0)
        at com.hypelabs.hype.drivers.c.c(Unknown Source:0)
        at com.hypelabs.hype.drivers.c.a(Unknown Source:0)
        at com.hypelabs.hype.drivers.Commons.StateManager.a(Unknown Source:0)
        at com.hypelabs.hype.drivers.c$1.run(Unknown Source:0)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

Beliving the app might have trouble running on the emulator given the lack of Bluetooth support I tried on 2 different devices and faced with the following outcome:
![screenshot_20180609-193829](https://user-images.githubusercontent.com/24616975/41286696-feb58e48-6e5d-11e8-8cea-771af4765113.jpg)

There's no error displayed in the logcat and the app doesnt crash on the devices.
The devices themselves were running Android **API 27 and 23**.

I followed all the instructions given in your repo and I'm unsure what to do.

**Comment by Hype-Labs** [comment]
We're working on fixing that specific crash, but either way the SDK does not work on the Android simulator. The emulator is not capable of accessing the hardware interfaces, thus communication is not possible. Regarding the other issue, could you please provide the brand and model of the devices involved?

**Comment by n-jay** [comment]
Noted about the emulator. It would be best if you could include that in you documentation.
As for the devices I tested the app on, they are as follows:

1. OnePlus 5T running OxygenOS 5.1.2 (based on Android 8.1)
2. Huawei Y5 II running EMUI 4.1.3 (based on Android 6.0)

While I do have another device based on Android 5.0, I gave it the benefit of the doubt and didn't test on it since the targetedSdkVersion is 23.

**Comment by 5abbagh** [comment]
Hello,
The same problem appears with me when running on android emulator with different API versions tested.
So is there no other way to test the SDK other than on real devices?
In that case is there also a restriction on the API version to run the SDK properly?

**Comment by n-jay** [comment]
@Ali-Sabbagh apparently the SDK is not supported on emulators due to the lack of Bluetooth.
It would have been better if they mentioned that in their documentation.
But the funny thing is while there aren't any crashes the app doesn't render anything on Hardware devices.
I know this isn't localized to a single device or Android version as mentioned in a comment above.
Still waiting for a fix.

**Comment by Hype-Labs** [comment]
Hi guys,

@n-jay you're right, it's not localized for a specific device, but Android's vendor diversity bears this type of concerns. Knowing the hardware often helps to tackle these problems.

@Ali-Sabbagh I think there's no other way, but I'll confirm.

The team is already looking into this. I'll let you guys know ASAP. In the meanwhile we're also adding this info to the docs, that makes perfect sense.

**Comment by Hype-Labs** [comment]
@n-jay the supported Android API version is 16+

**Comment by Hype-Labs** [comment]
To complete the previous answer. The SDK support is for Android 16+, but Bluetooth is only supported for 21+. Between the two, only Infrastructure Wi-Fi is supported by the SDK. It still holds that it doesn't work on the simulator, only real devices.

**Comment by n-jay** [comment]
@Hype-Labs thanks for the quick response!
I'll test it out once more and close this issue once I confirm the app's working state :+1:

**Comment by Hype-Labs** [comment]
@n-jay great! I'll be looking forward.

**Comment by n-jay** [comment]
@Hype-Labs in the meantime created a Pull Request with an update to the readme.md file which can be found here: https://github.com/Hype-Labs/HypeChatDemo.android/pull/7.
Included instructions only to run the app on hardware devices.

**Comment by n-jay** [comment]
Issue resolved, app successfully opens in the hardware device.

**Comment by Shubham-Das** [comment]
No dude why
